import type { ConverterUnit } from "../types";

export const areaUnits: ConverterUnit[] = [
  {
    name: "Square Meters",
    symbol: "m²",
    toBase: 1,
    category: "metric",
    kind: "linear",
  },
  {
    name: "Square Kilometers",
    symbol: "km²",
    toBase: 1000000,
    category: "metric",
    kind: "linear",
  },
  {
    name: "Square Centimeters",
    symbol: "cm²",
    toBase: 0.0001,
    category: "metric",
    kind: "linear",
  },
  {
    name: "Square Millimeters",
    symbol: "mm²",
    toBase: 0.000001,
    category: "metric",
    kind: "linear",
  },
  {
    name: "Square Feet",
    symbol: "ft²",
    toBase: 0.092903,
    category: "imperial",
    kind: "linear",
  },
  {
    name: "Square Yards",
    symbol: "yd²",
    toBase: 0.836127,
    category: "imperial",
    kind: "linear",
  },
  {
    name: "Square Inches",
    symbol: "in²",
    toBase: 0.00064516,
    category: "imperial",
    kind: "linear",
  },
  {
    name: "Square Miles",
    symbol: "mi²",
    toBase: 2589988.11,
    category: "imperial",
    kind: "linear",
  },
  {
    name: "Acres",
    symbol: "ac",
    toBase: 4046.86,
    category: "imperial",
    kind: "linear",
  },
  { name: "Hectares", symbol: "ha", toBase: 10000, category: "metric", kind: "linear" },
  {
    name: "Square Nautical Miles",
    symbol: "nmi²",
    toBase: 3429904,
    category: "nautical",
    kind: "linear",
  },
  {
    name: "Square Astronomical Units",
    symbol: "AU²",
    toBase: 2.237e22,
    category: "astronomical",
    kind: "linear",
  },
  {
    name: "Square Light Years",
    symbol: "ly²",
    toBase: 8.95e31,
    category: "astronomical",
    kind: "linear",
  },
  {
    name: "Square Parsecs",
    symbol: "pc²",
    toBase: 9.52e32,
    category: "astronomical",
    kind: "linear",
  },
  { name: "Barns", symbol: "b", toBase: 1e-28, category: "scientific", kind: "linear" },
  {
    name: "Square Angstroms",
    symbol: "Å²",
    toBase: 1e-20,
    category: "scientific",
    kind: "linear",
  },
];
