import type { ConverterUnit } from "../types";

export const shoeSizeUnits: ConverterUnit[] = [
  {
    name: "US Men",
    symbol: "US M",
    toBase: (value) => value * 25.4 + 22.86,
    fromBase: (mm) => (mm - 22.86) / 25.4,
    category: "north-america",
    kind: "affine",
    step: 0.5,
  },
  {
    name: "US Women",
    symbol: "US W",
    toBase: (value) => value * 25.4 + 20.32,
    fromBase: (mm) => (mm - 20.32) / 25.4,
    category: "north-america",
    kind: "affine",
    step: 0.5,
  },
  {
    name: "UK",
    symbol: "UK",
    toBase: (value) => value * 25.4 + 25.4,
    fromBase: (mm) => (mm - 25.4) / 25.4,
    category: "europe",
    kind: "affine",
    step: 0.5,
  },
  {
    name: "EU",
    symbol: "EU",
    toBase: (value) => value * 6.67 + 20.32,
    fromBase: (mm) => (mm - 20.32) / 6.67,
    category: "europe",
    kind: "affine",
    step: 1,
  },
  {
    name: "JP/CM",
    symbol: "JP",
    toBase: (value) => value * 10,
    fromBase: (mm) => mm / 10,
    category: "asia",
    kind: "affine",
    step: 0.5,
  },
  {
    name: "AU",
    symbol: "AU",
    toBase: (value) => value * 25.4 + 25.4,
    fromBase: (mm) => (mm - 25.4) / 25.4,
    category: "oceania",
    kind: "affine",
    step: 0.5,
  },
  {
    name: "MX",
    symbol: "MX",
    toBase: (value) => value * 25.4 + 22.86,
    fromBase: (mm) => (mm - 22.86) / 25.4,
    category: "latin-america",
    kind: "affine",
    step: 0.5,
  },
  {
    name: "BR",
    symbol: "BR",
    toBase: (value) => value * 25.4 + 22.86,
    fromBase: (mm) => (mm - 22.86) / 25.4,
    category: "latin-america",
    kind: "affine",
    step: 0.5,
  },
];
