import type { ConverterUnit } from "../types";

export const speedUnits: ConverterUnit[] = [
  {
    name: "Meters per Second",
    symbol: "m/s",
    toBase: 1,
    category: "metric",
    kind: "linear",
  },
  {
    name: "Kilometers per Hour",
    symbol: "km/h",
    toBase: 0.277778,
    category: "metric",
    kind: "linear",
  },
  {
    name: "Miles per Hour",
    symbol: "mph",
    toBase: 0.44704,
    category: "imperial",
    kind: "linear",
  },
  {
    name: "Knots",
    symbol: "kn",
    toBase: 0.514444,
    category: "nautical",
    kind: "linear",
  },
  {
    name: "Feet per Second",
    symbol: "ft/s",
    toBase: 0.3048,
    category: "imperial",
    kind: "linear",
  },
  {
    name: "Kilometers per Second",
    symbol: "km/s",
    toBase: 1000,
    category: "metric",
    kind: "linear",
  },
  {
    name: "Centimeters per Second",
    symbol: "cm/s",
    toBase: 0.01,
    category: "metric",
    kind: "linear",
  },
  {
    name: "Mach Number",
    symbol: "M",
    toBase: 343,
    category: "scientific",
    kind: "linear",
  },
  {
    name: "Speed of Light",
    symbol: "c",
    toBase: 299792458,
    category: "scientific",
    kind: "linear",
  },
  {
    name: "Speed of Sound",
    symbol: "vs",
    toBase: 343,
    category: "scientific",
    kind: "linear",
  },
  {
    name: "Yards per Second",
    symbol: "yd/s",
    toBase: 0.9144,
    category: "imperial",
    kind: "linear",
  },
  {
    name: "Inches per Second",
    symbol: "in/s",
    toBase: 0.0254,
    category: "imperial",
    kind: "linear",
  },
  {
    name: "Miles per Second",
    symbol: "mi/s",
    toBase: 1609.344,
    category: "imperial",
    kind: "linear",
  },
  {
    name: "Nautical Miles per Hour",
    symbol: "nmi/h",
    toBase: 0.514444,
    category: "nautical",
    kind: "linear",
  },
  {
    name: "Furlongs per Fortnight",
    symbol: "fur/ftn",
    toBase: 0.0001663095,
    category: "historical",
    kind: "linear",
  },
  {
    name: "Beard Seconds",
    symbol: "beard-s",
    toBase: 5.08e-9,
    category: "scientific",
    kind: "linear",
  },
];
