import type { ConverterUnit } from "../types";

export const timeUnits: ConverterUnit[] = [
  { name: "Seconds", symbol: "s", toBase: 1, category: "base", kind: "linear" },
  { name: "Minutes", symbol: "min", toBase: 60, category: "base", kind: "linear" },
  { name: "Hours", symbol: "h", toBase: 3600, category: "base", kind: "linear" },
  { name: "Days", symbol: "d", toBase: 86400, category: "base", kind: "linear" },
  { name: "Weeks", symbol: "wk", toBase: 604800, category: "base", kind: "linear" },
  { name: "Months", symbol: "mo", toBase: 2592000, category: "calendar", kind: "linear" },
  { name: "Years", symbol: "yr", toBase: 31536000, category: "calendar", kind: "linear" },
  {
    name: "Decades",
    symbol: "dec",
    toBase: 315360000,
    category: "calendar",
    kind: "linear",
  },
  {
    name: "Centuries",
    symbol: "cent",
    toBase: 3153600000,
    category: "calendar",
    kind: "linear",
  },
  {
    name: "Millennia",
    symbol: "mill",
    toBase: 31536000000,
    category: "calendar",
    kind: "linear",
  },
  {
    name: "Milliseconds",
    symbol: "ms",
    toBase: 0.001,
    category: "precision",
    kind: "linear",
  },
  {
    name: "Microseconds",
    symbol: "μs",
    toBase: 0.000001,
    category: "precision",
    kind: "linear",
  },
  {
    name: "Nanoseconds",
    symbol: "ns",
    toBase: 0.000000001,
    category: "precision",
    kind: "linear",
  },
  {
    name: "Picoseconds",
    symbol: "ps",
    toBase: 0.000000000001,
    category: "precision",
    kind: "linear",
  },
  {
    name: "Femtoseconds",
    symbol: "fs",
    toBase: 0.000000000000001,
    category: "precision",
    kind: "linear",
  },
  {
    name: "Attoseconds",
    symbol: "as",
    toBase: 0.000000000000000001,
    category: "precision",
    kind: "linear",
  },
  {
    name: "Planck Time",
    symbol: "tP",
    toBase: 5.39e-44,
    category: "scientific",
    kind: "linear",
  },
  {
    name: "Lunar Month",
    symbol: "lunar",
    toBase: 2551442.8,
    category: "astronomical",
    kind: "linear",
  },
  {
    name: "Solar Year",
    symbol: "solar",
    toBase: 31556925.2,
    category: "astronomical",
    kind: "linear",
  },
  {
    name: "Sidereal Day",
    symbol: "sidereal",
    toBase: 86164.1,
    category: "astronomical",
    kind: "linear",
  },
  {
    name: "Julian Year",
    symbol: "julian",
    toBase: 31557600,
    category: "astronomical",
    kind: "linear",
  },
];
