/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeightConversionRouteImport } from './routes/weight-conversion'
import { Route as UuidGeneratorRouteImport } from './routes/uuid-generator'
import { Route as UrlEncoderRouteImport } from './routes/url-encoder'
import { Route as UnixTimestampRouteImport } from './routes/unix-timestamp'
import { Route as TimeConversionRouteImport } from './routes/time-conversion'
import { Route as TemperatureConversionRouteImport } from './routes/temperature-conversion'
import { Route as SpeedConversionRouteImport } from './routes/speed-conversion'
import { Route as ShoeSizeConversionRouteImport } from './routes/shoe-size-conversion'
import { Route as SalaryCalculationRouteImport } from './routes/salary-calculation'
import { Route as RegexTesterRouteImport } from './routes/regex-tester'
import { Route as QrCodeGeneratorRouteImport } from './routes/qr-code-generator'
import { Route as PrimeNumberCheckerRouteImport } from './routes/prime-number-checker'
import { Route as PomodoroTimerRouteImport } from './routes/pomodoro-timer'
import { Route as PhoneNumberParserRouteImport } from './routes/phone-number-parser'
import { Route as PayrollGeneratorRouteImport } from './routes/payroll-generator'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as MatrixCalculatorRouteImport } from './routes/matrix-calculator'
import { Route as MarkDownEditorRouteImport } from './routes/mark-down-editor'
import { Route as LoanCalculatorRouteImport } from './routes/loan-calculator'
import { Route as LengthConversionRouteImport } from './routes/length-conversion'
import { Route as JwtDecoderRouteImport } from './routes/jwt-decoder'
import { Route as JsonValidatorRouteImport } from './routes/json-validator'
import { Route as FakeHackerSimulatorRouteImport } from './routes/fake-hacker-simulator'
import { Route as EthiopianCalendarRouteImport } from './routes/ethiopian-calendar'
import { Route as EmojiPickerRouteImport } from './routes/emoji-picker'
import { Route as DataStorageConversionRouteImport } from './routes/data-storage-conversion'
import { Route as CurrencyConversionRouteImport } from './routes/currency-conversion'
import { Route as ColorToolsRouteImport } from './routes/color-tools'
import { Route as CheatSheetsRouteImport } from './routes/cheat-sheets'
import { Route as CharacterCounterRouteImport } from './routes/character-counter'
import { Route as BmiCalculationRouteImport } from './routes/bmi-calculation'
import { Route as Base64ToolRouteImport } from './routes/base64-tool'
import { Route as AsciiArtGeneratorRouteImport } from './routes/ascii-art-generator'
import { Route as AreaConversionRouteImport } from './routes/area-conversion'
import { Route as AgeAndDateConvertorsRouteImport } from './routes/age-and-date-convertors'
import { Route as IndexRouteImport } from './routes/index'

const WeightConversionRoute = WeightConversionRouteImport.update({
  id: '/weight-conversion',
  path: '/weight-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidGeneratorRoute = UuidGeneratorRouteImport.update({
  id: '/uuid-generator',
  path: '/uuid-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlEncoderRoute = UrlEncoderRouteImport.update({
  id: '/url-encoder',
  path: '/url-encoder',
  getParentRoute: () => rootRouteImport,
} as any)
const UnixTimestampRoute = UnixTimestampRouteImport.update({
  id: '/unix-timestamp',
  path: '/unix-timestamp',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeConversionRoute = TimeConversionRouteImport.update({
  id: '/time-conversion',
  path: '/time-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const TemperatureConversionRoute = TemperatureConversionRouteImport.update({
  id: '/temperature-conversion',
  path: '/temperature-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedConversionRoute = SpeedConversionRouteImport.update({
  id: '/speed-conversion',
  path: '/speed-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoeSizeConversionRoute = ShoeSizeConversionRouteImport.update({
  id: '/shoe-size-conversion',
  path: '/shoe-size-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryCalculationRoute = SalaryCalculationRouteImport.update({
  id: '/salary-calculation',
  path: '/salary-calculation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexTesterRoute = RegexTesterRouteImport.update({
  id: '/regex-tester',
  path: '/regex-tester',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeGeneratorRoute = QrCodeGeneratorRouteImport.update({
  id: '/qr-code-generator',
  path: '/qr-code-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeNumberCheckerRoute = PrimeNumberCheckerRouteImport.update({
  id: '/prime-number-checker',
  path: '/prime-number-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const PomodoroTimerRoute = PomodoroTimerRouteImport.update({
  id: '/pomodoro-timer',
  path: '/pomodoro-timer',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneNumberParserRoute = PhoneNumberParserRouteImport.update({
  id: '/phone-number-parser',
  path: '/phone-number-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollGeneratorRoute = PayrollGeneratorRouteImport.update({
  id: '/payroll-generator',
  path: '/payroll-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixCalculatorRoute = MatrixCalculatorRouteImport.update({
  id: '/matrix-calculator',
  path: '/matrix-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkDownEditorRoute = MarkDownEditorRouteImport.update({
  id: '/mark-down-editor',
  path: '/mark-down-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanCalculatorRoute = LoanCalculatorRouteImport.update({
  id: '/loan-calculator',
  path: '/loan-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LengthConversionRoute = LengthConversionRouteImport.update({
  id: '/length-conversion',
  path: '/length-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtDecoderRoute = JwtDecoderRouteImport.update({
  id: '/jwt-decoder',
  path: '/jwt-decoder',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonValidatorRoute = JsonValidatorRouteImport.update({
  id: '/json-validator',
  path: '/json-validator',
  getParentRoute: () => rootRouteImport,
} as any)
const FakeHackerSimulatorRoute = FakeHackerSimulatorRouteImport.update({
  id: '/fake-hacker-simulator',
  path: '/fake-hacker-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const EthiopianCalendarRoute = EthiopianCalendarRouteImport.update({
  id: '/ethiopian-calendar',
  path: '/ethiopian-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmojiPickerRoute = EmojiPickerRouteImport.update({
  id: '/emoji-picker',
  path: '/emoji-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStorageConversionRoute = DataStorageConversionRouteImport.update({
  id: '/data-storage-conversion',
  path: '/data-storage-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyConversionRoute = CurrencyConversionRouteImport.update({
  id: '/currency-conversion',
  path: '/currency-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorToolsRoute = ColorToolsRouteImport.update({
  id: '/color-tools',
  path: '/color-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatSheetsRoute = CheatSheetsRouteImport.update({
  id: '/cheat-sheets',
  path: '/cheat-sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterCounterRoute = CharacterCounterRouteImport.update({
  id: '/character-counter',
  path: '/character-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const BmiCalculationRoute = BmiCalculationRouteImport.update({
  id: '/bmi-calculation',
  path: '/bmi-calculation',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64ToolRoute = Base64ToolRouteImport.update({
  id: '/base64-tool',
  path: '/base64-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const AsciiArtGeneratorRoute = AsciiArtGeneratorRouteImport.update({
  id: '/ascii-art-generator',
  path: '/ascii-art-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaConversionRoute = AreaConversionRouteImport.update({
  id: '/area-conversion',
  path: '/area-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeAndDateConvertorsRoute = AgeAndDateConvertorsRouteImport.update({
  id: '/age-and-date-convertors',
  path: '/age-and-date-convertors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/age-and-date-convertors': typeof AgeAndDateConvertorsRoute
  '/area-conversion': typeof AreaConversionRoute
  '/ascii-art-generator': typeof AsciiArtGeneratorRoute
  '/base64-tool': typeof Base64ToolRoute
  '/bmi-calculation': typeof BmiCalculationRoute
  '/character-counter': typeof CharacterCounterRoute
  '/cheat-sheets': typeof CheatSheetsRoute
  '/color-tools': typeof ColorToolsRoute
  '/currency-conversion': typeof CurrencyConversionRoute
  '/data-storage-conversion': typeof DataStorageConversionRoute
  '/emoji-picker': typeof EmojiPickerRoute
  '/ethiopian-calendar': typeof EthiopianCalendarRoute
  '/fake-hacker-simulator': typeof FakeHackerSimulatorRoute
  '/json-validator': typeof JsonValidatorRoute
  '/jwt-decoder': typeof JwtDecoderRoute
  '/length-conversion': typeof LengthConversionRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/mark-down-editor': typeof MarkDownEditorRoute
  '/matrix-calculator': typeof MatrixCalculatorRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/payroll-generator': typeof PayrollGeneratorRoute
  '/phone-number-parser': typeof PhoneNumberParserRoute
  '/pomodoro-timer': typeof PomodoroTimerRoute
  '/prime-number-checker': typeof PrimeNumberCheckerRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/regex-tester': typeof RegexTesterRoute
  '/salary-calculation': typeof SalaryCalculationRoute
  '/shoe-size-conversion': typeof ShoeSizeConversionRoute
  '/speed-conversion': typeof SpeedConversionRoute
  '/temperature-conversion': typeof TemperatureConversionRoute
  '/time-conversion': typeof TimeConversionRoute
  '/unix-timestamp': typeof UnixTimestampRoute
  '/url-encoder': typeof UrlEncoderRoute
  '/uuid-generator': typeof UuidGeneratorRoute
  '/weight-conversion': typeof WeightConversionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age-and-date-convertors': typeof AgeAndDateConvertorsRoute
  '/area-conversion': typeof AreaConversionRoute
  '/ascii-art-generator': typeof AsciiArtGeneratorRoute
  '/base64-tool': typeof Base64ToolRoute
  '/bmi-calculation': typeof BmiCalculationRoute
  '/character-counter': typeof CharacterCounterRoute
  '/cheat-sheets': typeof CheatSheetsRoute
  '/color-tools': typeof ColorToolsRoute
  '/currency-conversion': typeof CurrencyConversionRoute
  '/data-storage-conversion': typeof DataStorageConversionRoute
  '/emoji-picker': typeof EmojiPickerRoute
  '/ethiopian-calendar': typeof EthiopianCalendarRoute
  '/fake-hacker-simulator': typeof FakeHackerSimulatorRoute
  '/json-validator': typeof JsonValidatorRoute
  '/jwt-decoder': typeof JwtDecoderRoute
  '/length-conversion': typeof LengthConversionRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/mark-down-editor': typeof MarkDownEditorRoute
  '/matrix-calculator': typeof MatrixCalculatorRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/payroll-generator': typeof PayrollGeneratorRoute
  '/phone-number-parser': typeof PhoneNumberParserRoute
  '/pomodoro-timer': typeof PomodoroTimerRoute
  '/prime-number-checker': typeof PrimeNumberCheckerRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/regex-tester': typeof RegexTesterRoute
  '/salary-calculation': typeof SalaryCalculationRoute
  '/shoe-size-conversion': typeof ShoeSizeConversionRoute
  '/speed-conversion': typeof SpeedConversionRoute
  '/temperature-conversion': typeof TemperatureConversionRoute
  '/time-conversion': typeof TimeConversionRoute
  '/unix-timestamp': typeof UnixTimestampRoute
  '/url-encoder': typeof UrlEncoderRoute
  '/uuid-generator': typeof UuidGeneratorRoute
  '/weight-conversion': typeof WeightConversionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/age-and-date-convertors': typeof AgeAndDateConvertorsRoute
  '/area-conversion': typeof AreaConversionRoute
  '/ascii-art-generator': typeof AsciiArtGeneratorRoute
  '/base64-tool': typeof Base64ToolRoute
  '/bmi-calculation': typeof BmiCalculationRoute
  '/character-counter': typeof CharacterCounterRoute
  '/cheat-sheets': typeof CheatSheetsRoute
  '/color-tools': typeof ColorToolsRoute
  '/currency-conversion': typeof CurrencyConversionRoute
  '/data-storage-conversion': typeof DataStorageConversionRoute
  '/emoji-picker': typeof EmojiPickerRoute
  '/ethiopian-calendar': typeof EthiopianCalendarRoute
  '/fake-hacker-simulator': typeof FakeHackerSimulatorRoute
  '/json-validator': typeof JsonValidatorRoute
  '/jwt-decoder': typeof JwtDecoderRoute
  '/length-conversion': typeof LengthConversionRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/mark-down-editor': typeof MarkDownEditorRoute
  '/matrix-calculator': typeof MatrixCalculatorRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/payroll-generator': typeof PayrollGeneratorRoute
  '/phone-number-parser': typeof PhoneNumberParserRoute
  '/pomodoro-timer': typeof PomodoroTimerRoute
  '/prime-number-checker': typeof PrimeNumberCheckerRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/regex-tester': typeof RegexTesterRoute
  '/salary-calculation': typeof SalaryCalculationRoute
  '/shoe-size-conversion': typeof ShoeSizeConversionRoute
  '/speed-conversion': typeof SpeedConversionRoute
  '/temperature-conversion': typeof TemperatureConversionRoute
  '/time-conversion': typeof TimeConversionRoute
  '/unix-timestamp': typeof UnixTimestampRoute
  '/url-encoder': typeof UrlEncoderRoute
  '/uuid-generator': typeof UuidGeneratorRoute
  '/weight-conversion': typeof WeightConversionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/age-and-date-convertors'
    | '/area-conversion'
    | '/ascii-art-generator'
    | '/base64-tool'
    | '/bmi-calculation'
    | '/character-counter'
    | '/cheat-sheets'
    | '/color-tools'
    | '/currency-conversion'
    | '/data-storage-conversion'
    | '/emoji-picker'
    | '/ethiopian-calendar'
    | '/fake-hacker-simulator'
    | '/json-validator'
    | '/jwt-decoder'
    | '/length-conversion'
    | '/loan-calculator'
    | '/mark-down-editor'
    | '/matrix-calculator'
    | '/password-generator'
    | '/payroll-generator'
    | '/phone-number-parser'
    | '/pomodoro-timer'
    | '/prime-number-checker'
    | '/qr-code-generator'
    | '/regex-tester'
    | '/salary-calculation'
    | '/shoe-size-conversion'
    | '/speed-conversion'
    | '/temperature-conversion'
    | '/time-conversion'
    | '/unix-timestamp'
    | '/url-encoder'
    | '/uuid-generator'
    | '/weight-conversion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/age-and-date-convertors'
    | '/area-conversion'
    | '/ascii-art-generator'
    | '/base64-tool'
    | '/bmi-calculation'
    | '/character-counter'
    | '/cheat-sheets'
    | '/color-tools'
    | '/currency-conversion'
    | '/data-storage-conversion'
    | '/emoji-picker'
    | '/ethiopian-calendar'
    | '/fake-hacker-simulator'
    | '/json-validator'
    | '/jwt-decoder'
    | '/length-conversion'
    | '/loan-calculator'
    | '/mark-down-editor'
    | '/matrix-calculator'
    | '/password-generator'
    | '/payroll-generator'
    | '/phone-number-parser'
    | '/pomodoro-timer'
    | '/prime-number-checker'
    | '/qr-code-generator'
    | '/regex-tester'
    | '/salary-calculation'
    | '/shoe-size-conversion'
    | '/speed-conversion'
    | '/temperature-conversion'
    | '/time-conversion'
    | '/unix-timestamp'
    | '/url-encoder'
    | '/uuid-generator'
    | '/weight-conversion'
  id:
    | '__root__'
    | '/'
    | '/age-and-date-convertors'
    | '/area-conversion'
    | '/ascii-art-generator'
    | '/base64-tool'
    | '/bmi-calculation'
    | '/character-counter'
    | '/cheat-sheets'
    | '/color-tools'
    | '/currency-conversion'
    | '/data-storage-conversion'
    | '/emoji-picker'
    | '/ethiopian-calendar'
    | '/fake-hacker-simulator'
    | '/json-validator'
    | '/jwt-decoder'
    | '/length-conversion'
    | '/loan-calculator'
    | '/mark-down-editor'
    | '/matrix-calculator'
    | '/password-generator'
    | '/payroll-generator'
    | '/phone-number-parser'
    | '/pomodoro-timer'
    | '/prime-number-checker'
    | '/qr-code-generator'
    | '/regex-tester'
    | '/salary-calculation'
    | '/shoe-size-conversion'
    | '/speed-conversion'
    | '/temperature-conversion'
    | '/time-conversion'
    | '/unix-timestamp'
    | '/url-encoder'
    | '/uuid-generator'
    | '/weight-conversion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgeAndDateConvertorsRoute: typeof AgeAndDateConvertorsRoute
  AreaConversionRoute: typeof AreaConversionRoute
  AsciiArtGeneratorRoute: typeof AsciiArtGeneratorRoute
  Base64ToolRoute: typeof Base64ToolRoute
  BmiCalculationRoute: typeof BmiCalculationRoute
  CharacterCounterRoute: typeof CharacterCounterRoute
  CheatSheetsRoute: typeof CheatSheetsRoute
  ColorToolsRoute: typeof ColorToolsRoute
  CurrencyConversionRoute: typeof CurrencyConversionRoute
  DataStorageConversionRoute: typeof DataStorageConversionRoute
  EmojiPickerRoute: typeof EmojiPickerRoute
  EthiopianCalendarRoute: typeof EthiopianCalendarRoute
  FakeHackerSimulatorRoute: typeof FakeHackerSimulatorRoute
  JsonValidatorRoute: typeof JsonValidatorRoute
  JwtDecoderRoute: typeof JwtDecoderRoute
  LengthConversionRoute: typeof LengthConversionRoute
  LoanCalculatorRoute: typeof LoanCalculatorRoute
  MarkDownEditorRoute: typeof MarkDownEditorRoute
  MatrixCalculatorRoute: typeof MatrixCalculatorRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  PayrollGeneratorRoute: typeof PayrollGeneratorRoute
  PhoneNumberParserRoute: typeof PhoneNumberParserRoute
  PomodoroTimerRoute: typeof PomodoroTimerRoute
  PrimeNumberCheckerRoute: typeof PrimeNumberCheckerRoute
  QrCodeGeneratorRoute: typeof QrCodeGeneratorRoute
  RegexTesterRoute: typeof RegexTesterRoute
  SalaryCalculationRoute: typeof SalaryCalculationRoute
  ShoeSizeConversionRoute: typeof ShoeSizeConversionRoute
  SpeedConversionRoute: typeof SpeedConversionRoute
  TemperatureConversionRoute: typeof TemperatureConversionRoute
  TimeConversionRoute: typeof TimeConversionRoute
  UnixTimestampRoute: typeof UnixTimestampRoute
  UrlEncoderRoute: typeof UrlEncoderRoute
  UuidGeneratorRoute: typeof UuidGeneratorRoute
  WeightConversionRoute: typeof WeightConversionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weight-conversion': {
      id: '/weight-conversion'
      path: '/weight-conversion'
      fullPath: '/weight-conversion'
      preLoaderRoute: typeof WeightConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuid-generator': {
      id: '/uuid-generator'
      path: '/uuid-generator'
      fullPath: '/uuid-generator'
      preLoaderRoute: typeof UuidGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-encoder': {
      id: '/url-encoder'
      path: '/url-encoder'
      fullPath: '/url-encoder'
      preLoaderRoute: typeof UrlEncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unix-timestamp': {
      id: '/unix-timestamp'
      path: '/unix-timestamp'
      fullPath: '/unix-timestamp'
      preLoaderRoute: typeof UnixTimestampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-conversion': {
      id: '/time-conversion'
      path: '/time-conversion'
      fullPath: '/time-conversion'
      preLoaderRoute: typeof TimeConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temperature-conversion': {
      id: '/temperature-conversion'
      path: '/temperature-conversion'
      fullPath: '/temperature-conversion'
      preLoaderRoute: typeof TemperatureConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed-conversion': {
      id: '/speed-conversion'
      path: '/speed-conversion'
      fullPath: '/speed-conversion'
      preLoaderRoute: typeof SpeedConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoe-size-conversion': {
      id: '/shoe-size-conversion'
      path: '/shoe-size-conversion'
      fullPath: '/shoe-size-conversion'
      preLoaderRoute: typeof ShoeSizeConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-calculation': {
      id: '/salary-calculation'
      path: '/salary-calculation'
      fullPath: '/salary-calculation'
      preLoaderRoute: typeof SalaryCalculationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex-tester': {
      id: '/regex-tester'
      path: '/regex-tester'
      fullPath: '/regex-tester'
      preLoaderRoute: typeof RegexTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-generator': {
      id: '/qr-code-generator'
      path: '/qr-code-generator'
      fullPath: '/qr-code-generator'
      preLoaderRoute: typeof QrCodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prime-number-checker': {
      id: '/prime-number-checker'
      path: '/prime-number-checker'
      fullPath: '/prime-number-checker'
      preLoaderRoute: typeof PrimeNumberCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomodoro-timer': {
      id: '/pomodoro-timer'
      path: '/pomodoro-timer'
      fullPath: '/pomodoro-timer'
      preLoaderRoute: typeof PomodoroTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-number-parser': {
      id: '/phone-number-parser'
      path: '/phone-number-parser'
      fullPath: '/phone-number-parser'
      preLoaderRoute: typeof PhoneNumberParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-generator': {
      id: '/payroll-generator'
      path: '/payroll-generator'
      fullPath: '/payroll-generator'
      preLoaderRoute: typeof PayrollGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix-calculator': {
      id: '/matrix-calculator'
      path: '/matrix-calculator'
      fullPath: '/matrix-calculator'
      preLoaderRoute: typeof MatrixCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mark-down-editor': {
      id: '/mark-down-editor'
      path: '/mark-down-editor'
      fullPath: '/mark-down-editor'
      preLoaderRoute: typeof MarkDownEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-calculator': {
      id: '/loan-calculator'
      path: '/loan-calculator'
      fullPath: '/loan-calculator'
      preLoaderRoute: typeof LoanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/length-conversion': {
      id: '/length-conversion'
      path: '/length-conversion'
      fullPath: '/length-conversion'
      preLoaderRoute: typeof LengthConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt-decoder': {
      id: '/jwt-decoder'
      path: '/jwt-decoder'
      fullPath: '/jwt-decoder'
      preLoaderRoute: typeof JwtDecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-validator': {
      id: '/json-validator'
      path: '/json-validator'
      fullPath: '/json-validator'
      preLoaderRoute: typeof JsonValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fake-hacker-simulator': {
      id: '/fake-hacker-simulator'
      path: '/fake-hacker-simulator'
      fullPath: '/fake-hacker-simulator'
      preLoaderRoute: typeof FakeHackerSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethiopian-calendar': {
      id: '/ethiopian-calendar'
      path: '/ethiopian-calendar'
      fullPath: '/ethiopian-calendar'
      preLoaderRoute: typeof EthiopianCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emoji-picker': {
      id: '/emoji-picker'
      path: '/emoji-picker'
      fullPath: '/emoji-picker'
      preLoaderRoute: typeof EmojiPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-storage-conversion': {
      id: '/data-storage-conversion'
      path: '/data-storage-conversion'
      fullPath: '/data-storage-conversion'
      preLoaderRoute: typeof DataStorageConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency-conversion': {
      id: '/currency-conversion'
      path: '/currency-conversion'
      fullPath: '/currency-conversion'
      preLoaderRoute: typeof CurrencyConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-tools': {
      id: '/color-tools'
      path: '/color-tools'
      fullPath: '/color-tools'
      preLoaderRoute: typeof ColorToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheat-sheets': {
      id: '/cheat-sheets'
      path: '/cheat-sheets'
      fullPath: '/cheat-sheets'
      preLoaderRoute: typeof CheatSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-counter': {
      id: '/character-counter'
      path: '/character-counter'
      fullPath: '/character-counter'
      preLoaderRoute: typeof CharacterCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmi-calculation': {
      id: '/bmi-calculation'
      path: '/bmi-calculation'
      fullPath: '/bmi-calculation'
      preLoaderRoute: typeof BmiCalculationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64-tool': {
      id: '/base64-tool'
      path: '/base64-tool'
      fullPath: '/base64-tool'
      preLoaderRoute: typeof Base64ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascii-art-generator': {
      id: '/ascii-art-generator'
      path: '/ascii-art-generator'
      fullPath: '/ascii-art-generator'
      preLoaderRoute: typeof AsciiArtGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-conversion': {
      id: '/area-conversion'
      path: '/area-conversion'
      fullPath: '/area-conversion'
      preLoaderRoute: typeof AreaConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-and-date-convertors': {
      id: '/age-and-date-convertors'
      path: '/age-and-date-convertors'
      fullPath: '/age-and-date-convertors'
      preLoaderRoute: typeof AgeAndDateConvertorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgeAndDateConvertorsRoute: AgeAndDateConvertorsRoute,
  AreaConversionRoute: AreaConversionRoute,
  AsciiArtGeneratorRoute: AsciiArtGeneratorRoute,
  Base64ToolRoute: Base64ToolRoute,
  BmiCalculationRoute: BmiCalculationRoute,
  CharacterCounterRoute: CharacterCounterRoute,
  CheatSheetsRoute: CheatSheetsRoute,
  ColorToolsRoute: ColorToolsRoute,
  CurrencyConversionRoute: CurrencyConversionRoute,
  DataStorageConversionRoute: DataStorageConversionRoute,
  EmojiPickerRoute: EmojiPickerRoute,
  EthiopianCalendarRoute: EthiopianCalendarRoute,
  FakeHackerSimulatorRoute: FakeHackerSimulatorRoute,
  JsonValidatorRoute: JsonValidatorRoute,
  JwtDecoderRoute: JwtDecoderRoute,
  LengthConversionRoute: LengthConversionRoute,
  LoanCalculatorRoute: LoanCalculatorRoute,
  MarkDownEditorRoute: MarkDownEditorRoute,
  MatrixCalculatorRoute: MatrixCalculatorRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  PayrollGeneratorRoute: PayrollGeneratorRoute,
  PhoneNumberParserRoute: PhoneNumberParserRoute,
  PomodoroTimerRoute: PomodoroTimerRoute,
  PrimeNumberCheckerRoute: PrimeNumberCheckerRoute,
  QrCodeGeneratorRoute: QrCodeGeneratorRoute,
  RegexTesterRoute: RegexTesterRoute,
  SalaryCalculationRoute: SalaryCalculationRoute,
  ShoeSizeConversionRoute: ShoeSizeConversionRoute,
  SpeedConversionRoute: SpeedConversionRoute,
  TemperatureConversionRoute: TemperatureConversionRoute,
  TimeConversionRoute: TimeConversionRoute,
  UnixTimestampRoute: UnixTimestampRoute,
  UrlEncoderRoute: UrlEncoderRoute,
  UuidGeneratorRoute: UuidGeneratorRoute,
  WeightConversionRoute: WeightConversionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
